### ISSUE TITLE
Camera does not connect under linux 

### ISSUE THREAD

**Issue by mgraupe** [bothlab/pomidaq#6]
Hello, 

I managed to compile and install pomidaq on my laptop running Ubuntu 20.10 (Thinkpad X1 Carbon 6th Gen). pomidaq starts and works properly but the image displayed appears to be some random noise. Whether the DAQ is connected or not doesn't change the behavior of pomidaq (DAQ v3.3 with Miniscope V4). 

Which additional steps are required on linux to get pomidaq to connect to the daq? 

Thank you for your help in advance.

Cheers,
Michael

**Comment by ximion** [comment]
Actually none, this should work out of the box. Which version of PoMiDAQ did you build? Git master, or one of the releases?
Which camera ID did you select? Maybe it picked the internal camera and you need a higher ID to select the right one.
We actually tested PoMiDAQ on a ThinkPad E485, so I think it's unlikely that the computer is to blame here.
Could you post a screenshot of the noise, as well as maybe the log PoMiDAQ creates? (Just launch it from the command line)

**Comment by mgraupe** [comment]
Thank you for your prompt reply. 

Sorry, my bad! The described behavior occurred with ID 0, and since ID 1 gave an error, I didn't explore further. I could connect with the miniscope using ID 4. Works great. 

Thank you for making the control portable. I think it is the first time for me that I can pilot a piece of hardware from linux! 

Unrelated, is there a way to display the actual values of gain, EW lens setting and LED power in the GUI? 

Cheers,
Michael

**Comment by ximion** [comment]
> Unrelated, is there a way to display the actual values of gain, EW lens setting and LED power in the GUI?

Do you mean the values that are sent via USB, or do you just mean integer values for the sliders? The former isn't possible and will likely not be implemented (there's a bunch of abstraction on top of the actual communication), but the latter is on my todo list and isn't difficult to add.
